In [2]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations


ModuleNotFoundError: No module named 'viz'

In [ ]:
#How likely is it that you roll doubles when rolling two dice?

In [5]:
outcomes = [1,2,3,4,5,6]

In [12]:
rolls = np.random.choice(outcomes,10000 * 2).reshape(10000,2)

In [35]:
rolls

array([[4, 1],
       [1, 5],
       [5, 5],
       ...,
       [2, 5],
       [4, 6],
       [1, 3]])

In [43]:
df = pd.DataFrame(rolls)

In [51]:
dubs = df[df[0] == df[1]]

In [55]:
dubs[0].count()/df[0].count()

0.1641

In [56]:
#chance of rolling dubs is .1641

In [57]:
#If you flip 8 coins, what is the probability of getting exactly 3 heads?

In [58]:
outcomes = ['H','T']

In [91]:
flips = np.random.choice(outcomes,10000 * 8).reshape(10000,8)

In [61]:
df = pd.DataFrame(flips)

In [93]:
head_count = (flips == 'H').sum(axis=1)
head_count

array([5, 3, 1, ..., 2, 7, 3])

In [104]:
(head_count == 3).mean()

0.2237

In [105]:
#.2237 chance that you roll 3 heads

In [106]:
#What are the odds you get more than 3 heads?

In [107]:
(head_count >= 3).mean()

0.8576

In [108]:
#.8576 chance that you roll more than 3 heads

In [109]:
#There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [110]:
outcomes = ['W','W','W','D']

In [111]:
ad = np.random.choice(outcomes, 10000 * 2).reshape(10000,2)

In [112]:
ad

array([['W', 'W'],
       ['D', 'W'],
       ['W', 'W'],
       ...,
       ['W', 'W'],
       ['W', 'W'],
       ['W', 'W']], dtype='<U1')

In [114]:
df = pd.DataFrame(ad)

In [121]:
rep = df[(df[0]== 'D') & (df[1] == 'D')]

In [124]:
rep[0].count()/df[0].count()

0.0614

In [125]:
#Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [211]:
poptarts = np.random.normal(3,1.5,size=10000)

In [212]:
answer = (poptarts * 4.5) <= 16

In [213]:
answer.mean()

0.6455

In [ ]:
#there is about a 65% chance you can get a poptart on friday afternoon

In [165]:
#Compare Heights

#Men have an average height of 178 cm and standard deviation of 8cm.
#Women have a mean of 170, sd = 6cm.
#Since you have means and standard deviations, you can use np.random.normal to generate observations.
#If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?


In [193]:
man_heights = np.random.normal(178,8,size = 10000)
woman_heights = np.random.normal(170,6,size = 10000)

In [194]:
answer = woman_heights > man_heights

In [195]:
answer.mean()

0.2179

In [196]:
#there is about a 21% chance a random woman is taller than a random man

In [197]:
#When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue?

In [198]:
# odds 1/250 

In [235]:
1/250

0.004

In [236]:
p = .004

In [255]:
downloads = np.random.random((10000,50))

In [248]:
success = (downloads > .004).sum(axis=1) == 50

In [250]:
success.mean()

0.8135

In [ ]:
#81% chance everyone downloads

In [252]:
#100  

In [258]:
downloads = np.random.random((10000,100))

In [259]:
success = (downloads > .004).sum(axis=1) == 100

In [260]:
success.mean()

0.6623

In [261]:
#66%chance everyone downloads

In [262]:
#What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [263]:
downloads = np.random.random((10000,150))

In [264]:
failure = (downloads<.004).sum(axis=1) >=1

In [265]:
failure.mean()

0.4505

In [266]:
#there is about a 45% chance someone will fail a download out of 150 students

In [267]:
#How likely is it that 450 students all download anaconda without an issue?

In [270]:
downloads = np.random.random((10000,450))

In [271]:
success = (downloads > .004).sum(axis=1) == 450

In [273]:
success.mean()

0.1583

In [274]:
#there is about a 15 % chance3 all students can download anaconda without issue

In [275]:
#There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?



In [276]:
p = .7

In [277]:
days = np.random.random((10000,3))

In [278]:
no_truck = (days <= .3).sum(axis=1) == 3

In [279]:
no_truck.mean()

0.0276

In [280]:
#There is about a 2.7% percent chance you wont see a food truck over the course of 3 days

In [285]:
#How likely is it that a food truck will show up sometime this week? !using fresh 7 day week!

In [287]:
days = np.random.random((10000,7))

In [292]:
truck = (days >= .7).sum(axis=1) >= 1

In [293]:
truck.mean()

0.916

In [294]:
#there is about a 91% chance we see the food truck this week

In [295]:
#If 23 people are in the same room, what are the odds that two of them share a birthday? 

In [297]:
p = 1/365

In [371]:
p

0.0027397260273972603

In [393]:
bdays = np.random.random((100000,23))

array([[0.38170883, 0.26678721, 0.94382411, ..., 0.63230812, 0.3659434 ,
        0.85982491],
       [0.36666699, 0.94015863, 0.45881878, ..., 0.44955809, 0.77624077,
        0.05460001],
       [0.28796135, 0.19512923, 0.50867338, ..., 0.08303471, 0.67594449,
        0.28057735],
       ...,
       [0.44471703, 0.86905129, 0.16462443, ..., 0.03450086, 0.56227492,
        0.85427009],
       [0.42161136, 0.77121789, 0.48598237, ..., 0.5865146 , 0.36512283,
        0.51903699],
       [0.29661922, 0.06874358, 0.56891729, ..., 0.66301784, 0.94266316,
        0.99632865]])

In [392]:
shared.mean()

0.06104